# Generated by Django 5.0.4 on 2024-05-21 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="College",
            fields=[
                ("college_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                ("about", models.TextField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("B-Tech", "B-Tech"),
                            ("B-Architecture", "B-Architecture"),
                            ("Diploma", "Diploma"),
                            ("Medical", "Medical"),
                        ],
                        max_length=100,
                    ),
                ),
                ("added_date", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("rollno", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=100)),
                ("Phone", models.CharField(max_length=10)),
                (
                    "Stream",
                    models.CharField(
                        choices=[
                            ("Computer science", "computer science"),
                            ("Mechanical Engineering", "mechanical engineering"),
                            ("Electical Engineering", "electrical engineering"),
                            ("Civil Engineering", "civil engineering"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "college",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.college"
                    ),
                ),
            ],
        ),
    ]
