from django.urls import path, include  #path is used to define individual URL patterns  #include allows including other URL configurations.
from django.contrib.auth.models import User  # Correct import for User model
from api.views import CollegeViewSet,StudentViewSet#This imports the CollegeViewSet which is a Django REST Framework view set that handles CRUD operations for the College model.

from rest_framework import routers,serializers,viewsets   #Importing routers allows us to create a router that will automatically generate URL patterns for the view sets.

# Create a router and register our viewsets with it
router = routers.DefaultRouter()
router.register(r'colleges', CollegeViewSet) 
router.register(r'students',StudentViewSet)
#Registers the CollegeViewSet with the router under the URL prefix colleges. This means that DRF will handle all the URL routing for the CollegeViewSet, making endpoints like /colleges/, /colleges/{id}/, etc., available.

# The API URLs are now determined automatically by the router
urlpatterns = [
    path('', include(router.urls)), 
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]  #Includes all the URL patterns generated by the router at the root URL (''). This means that the URLs for the CollegeViewSet will be accessible directly under the base URL of your API.
#Includes the authentication URLs provided by DRF under the prefix api-auth/. This typically includes endpoints for login and logout, which are useful for managing user authentication in the API.
